### ISSUE TITLE
Update README on topical-guides vs understanding repository

### ISSUE THREAD

**Issue by rstoyanchev** [spring-guides/topical-guides#1]
https://github.com/spring-guides/understanding

**Comment by dsyer** [comment]
I assume this is obsolete?

**Comment by rstoyanchev** [comment]
Old for sure. I think the idea was to have some mention of how to decide which kind of guide to create since "understanding" guides are pretty similar in purpose but much shorter, more like side notes.

**Comment by dsyer** [comment]
See 9ce5b75
